### ISSUE TITLE
Cannot read property 'lineno' of undefined

### ISSUE THREAD

**Issue by renestalder** [LearnBoost/stylus#1754]
This error was already reported in previous versions and also fixed. But it seems It happens for me in 0.49.2.

```
   1| @import 'design';
--------------^
   2|

Cannot read property 'lineno' of undefined
```

It doesn't matter, which file I try to import. The file exists, has content and it worked some days ago. I'm not sure what I'm doing wrong or what has changed in my environment.

I'm using it together with the gulp stylus package.

**Comment by falafflepotatoe** [comment]
yea im getting to too when piping data from another nodejs app -- i think it might be a buffer too small problem -- if i paste the data into console after running stylus it compiles fine, if i write it as a glob (via pipe) from node it breaks. cheers

**Comment by falafflepotatoe** [comment]
i fixed it on my end by stripping trailing newlines, the CTRL+D char, and trailing tabs -- no longer happens

also it never happens if you are parsing a file

from stdin or gulp.pipe it seems the lookAhead() functions dont like whitespace at the end of the file/line

**Comment by Panya** [comment]
Should be fixed in the `dev` branch.
