### ISSUE TITLE
Watch and print do not play nice [cli tool]

### ISSUE THREAD

**Issue by TheAlphaNerd** [LearnBoost/stylus#1797]
if you attempt to use ```---watch``` and ```-p``` together the files never actually get watched, and the build never gets done :cry:

**Comment by TheAlphaNerd** [comment]
Truthfully as I have been digging through the cli I have noticed quite a few oddities... would the team be open to a rewrite in the future?

**Comment by TheAlphaNerd** [comment]
There is some documentation that this just will not work

--> https://github.com/LearnBoost/stylus/blob/master/bin/stylus#L336-L337

This seems like an odd thing to just "not work".  At least if it isn't working it should probably let the user know that thing are going to not work.

**Comment by Panya** [comment]
Well, to me it's quite a strange way to use CLI (`--watch` __and__ `--print` together). Because every time when you change a file it will be recompiled and you will get the same output again and again. But I agree with you, we should throw an error when these flags used together. I'll accept a PR.
