### ISSUE TITLE
Why does cli output to folders

### ISSUE THREAD

**Issue by TheAlphaNerd** [LearnBoost/stylus#1799]
The current interface seems very odd to me.  Why would you want to specify a path and not a file name.

Would the stylus team be open to changing the functionality of the cli to support outputting to a file?  We could offer a fall back to the original method of writing to a dir.

The logic for file output is a bit funky right now, and implementing something like this might make a larger scale refactor necessary

**Comment by Panya** [comment]
> The current interface seems very odd to me. Why would you want to specify a path and not a file name.

This interface supported from the first version of Stylus. And it allows to compile several files (and even dirs) in one run.

> Would the stylus team be open to changing the functionality of the cli to support outputting to a file?

We already have an issue for this (see #1672). Feel free to implement solution described in https://github.com/LearnBoost/stylus/issues/1672#issuecomment-53137689.

**Comment by TheAlphaNerd** [comment]
Oops... should have done a search against issues first.  This is going to be a very strange one to implement. (Due to multifile input vs single file and the way the CLI handles args).

I'll keep the conversation going in the other thread
