### ISSUE TITLE
Publishing next version

### ISSUE THREAD

**Issue by TheAlphaNerd** [LearnBoost/stylus#1804]
Hey All.  I was curious when you are publishing the next version of stylus.  There are two months of backlogged fixes that are not yet downstream and it is blocking my ability to land stylus into our project without needing gulp.

Thanks!

**Comment by stevelacy** [comment]
:+1:

**Comment by kizu** [comment]
We'll publish a new version later this week. Thanks for pinging!

**Comment by TheAlphaNerd** [comment]
is a new release dropping soon? Sorry to be that person.

**Comment by kizu** [comment]
stylus@0.50.0 published! Sorry for all the delays, really. And thank you, @TheAlphaNerd for all the PRs and being that person :)
