### ISSUE TITLE
@import fails after first request

### ISSUE THREAD

**Issue by stevekeiser** [LearnBoost/stylus#1806]
I'm noticing an issue introduced in 0.49.0 where, when multiple files request the same ```@import```, only the first file receives the import. All subsequent imports (for the same stylus file) fail silently. I'm guessing this may have something to do with import caching.

**Comment by Panya** [comment]
Can you show an example? All works fine with `cache: false` or `--disable-cache` flag?

**Comment by nfour** [comment]
Probably a dupe of #1777.

Really hope this gets fixed soon, it's limiting the scope of my Stylus projects modularity.

**Comment by Panya** [comment]
I can't fix it without a test case.

**Comment by Panya** [comment]
Oh, #1403 already fixed in the `dev` branch.

**Comment by Panya** [comment]
Duplicate of #1403.
