### ISSUE TITLE
Can't compile CSS while using ie hacks

### ISSUE THREAD

**Issue by sipayRT** [LearnBoost/stylus#1810]
For examlpe, with such code as:
```
.some class
{
    filter: alpha(opacity=0);
}
```
I got an error `Cannot call method 'toFixed' of undefined`

**Comment by Panya** [comment]
Yep, you should use unquote bif in this case:
```sass
.some class
{
    filter: unquote('alpha(opacity=0)');
}
```
The example covered in the documentation.

**Comment by sipayRT** [comment]
thanks!
