### ISSUE TITLE
How to iteratively nest selectors

### ISSUE THREAD

**Issue by bstro** [LearnBoost/stylus#1814]
Take a look at the following screenshot. You'll notice that I'm (rather repetitiously) trying to accomodate for a thread-like layout that continually indents by a linear amount with each hierarchical level. This list goes on well below the fold. Can anyone tell me how I might accomplish this in a cleaner, DRY-er way?

![screen shot 2015-01-14 at 8 47 45 pm](https://cloud.githubusercontent.com/assets/627290/5752644/e003d766-9c2e-11e4-9ce9-5b9f24ece5c3.png)

**Comment by Panya** [comment]
Something like:
```sass
.layerList-item
  position: relative
  margin: 0

  $selector = '&'
  for i in 1..4
    $selector += ' .layerList-item'
    $pad = (i * 20)

    {$selector} > .layer
      padding-left: 20px + $pad
      .layerList-title
        width: 185px - $pad
      & > .layerList-nestedToggle
        left: $pad - 3px
```
