### ISSUE TITLE
@support rule has error with `not` in complex rules

### ISSUE THREAD

**Issue by aaarichter** [LearnBoost/stylus#1815]
using stylus 0.49
the code
```stylus
@supports ( (background-blend-mode: normal) and ( not (mask-type: alpha) ) )
    select
        padding: 9px 16px 9px 10px
```

gives
```
>>    118| @supports ( (background-blend-mode: normal) and ( not (mask-type: alpha) ) )
>> --------------------------------------------------------^
>>    119|   select
>>    120|     padding: 9px 16px 9px 10px
>>
>> expected "ident", got "not"
```
or am I missing something? The documentation does only show simple support rules

**Comment by Panya** [comment]
Well, it's a bug. As temporary workaround you can use a variable with this condition:
```sass
$cond = '( (background-blend-mode: normal) and ( not (mask-type: alpha) ) )'
@supports $cond
    select
        padding: 9px 16px 9px 10px
```

**Comment by aaarichter** [comment]
thanks @Panya for the quick reply and the workaround - awesome

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. The fix will be in the next release.

**Comment by ethantw** [comment]
Hi,

I noticed that the `not` operator won’t work in `@media` query either. The workaround above somehow fails too. Do you mind taking a look into this? (Am using Stylus `0.54.5` here)

Thanks. 

<img width="344" alt="screen shot 2017-03-18 at 23 25 44" src="https://cloud.githubusercontent.com/assets/31068/24073445/8e171a6e-0c32-11e7-8877-9ae890bb0613.png">

```
expected "ident", got "not"
```

**Comment by ethantw** [comment]
I realised that in CSS, you’ll have to write `@media not all and (max-width: 768px)` for the logic to work (behaves like`@media (min-width: 769px)`), and it can be smoothly parsed via Stylus. I guess this is my fault. Sorry for your time.

**Comment by ethantw** [comment]
I realised that in CSS, you’ll have to write `@media not all and (max-width: 768px)` for the logic to work (behaves like`@media (min-width: 769px)`), and it can be smoothly parsed via Stylus. I guess this is my fault. Sorry for your time.
