### ISSUE TITLE
filter: contrast() doesn't work

### ISSUE THREAD

**Issue by Calvein** [LearnBoost/stylus#1816]
Same problem as #1335 and wasn't fix in #1340.

Error is:
```
TypeError: expected rgba or hsla, but got unit:200%
```

Spec: https://developer.mozilla.org/en-US/docs/Web/CSS/filter#contrast()

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. The fix will be in the next release.
