### ISSUE TITLE
functions defined in other files aren't properly imported if @require is nested

### ISSUE THREAD

**Issue by rschifflin** [LearnBoost/stylus#1823]
I've encountered some weird behavior when using an `@require` or `@import` statement nested below the root of a stylus file.
Given a file 'foo.styl'
```stylus
foo(a, b)
  -prefix-{a} b
  {a} b

bar()
  foo('bar', arguments)
```

I would expect these 4 stylus files to produce the same css:
```stylus
//1. require-outside.styl
@require 'foo'
.top-level-class
  div
    bar: 1 2 3
```

```stylus
//2. require-inside.styl
.top-level-class
  @require 'foo'
  div
    bar: 1 2 3
```

```stylus
//3. inline-outside.styl
foo(a, b)
  -prefix-{a} b
  {a} b

bar()
  foo('bar', arguments)

.top-level-class
  div
    bar: 1 2 3
```

```stylus
//4. inline-inside.styl
.top-level-class
  foo(a, b)
    -prefix-{a} b
    {a} b

  bar()
    foo('bar', arguments)

  div
    bar: 1 2 3
```

These should all produce
```css
.top-level-class div {
  -prefix-bar: 1 2 3;
  bar: 1 2 3;
}
```

And options 1, 3 and 4 do create that css. But option 2, where we `@require` below the root level, silently omits the call to `bar`, and the resulting css file is empty. In #1381 there is an old comment: "Currently Stylus supports @import and @require only on the root level. ", but the [docs](http://learnboost.github.io/stylus/docs/import.html) specify "Stylus supports block-level import. It means that you can use @import not only at root level, but also nested inside other selectors or at-rules."

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. This fix will be in the next release.
