### ISSUE TITLE
Is Stylus dead?

### ISSUE THREAD

**Issue by hworld** [LearnBoost/stylus#1824]
I'm not sure where to ask this, but is Stylus dead? I've written out a huge project in Stylus and keep getting bit by various bugs (mostly with `@extend` and `@media` queries), and I'm now wondering if I should be getting ready to port it all over to sass.

I see there is a 1.0rc branch that looks to have some nice commits to help tighten the syntax. And there's been a few commits on the dev branch, but it seems like nothing major. Just curious what the plans are with the project.

**Comment by brigand** [comment]
Also see [1.0 milestone][1], which seems to be nearly done (assuming that's accurate).

[1]: https://github.com/LearnBoost/stylus/milestones

**Comment by OctoD** [comment]
Stylus is alive. Devs and contributors are working and reworking stuff for the 1.0 release.

**Comment by Panya** [comment]
No. We just don't have much time to develop it currently. The nearest plan is to release 1.0.
