### ISSUE TITLE
Mixin variables do not get copied into {block}

### ISSUE THREAD

**Issue by FranzSkuffka** [LearnBoost/stylus#1826]
example:
http://codepen.io/franzskuffka/pen/myMvyj

**Comment by vendethiel** [comment]
Right, that's called lexical scoping. Seems to be a feature to me.

**Comment by FranzSkuffka** [comment]
From my perspective, the {block} is part of the code block/intuitive variable scope.
Is there another way to somehow pass variables from a mixin parameter into the {block} ?

**Comment by Panya** [comment]
Yep, lexical scoping. This is intended behavior. BTW Sass's `@content` works the same way.

**Comment by FranzSkuffka** [comment]
Is there a way to pass variables out of the lexical scope?

**Comment by Panya** [comment]
@FranzSkuffka for block mixins — no, but you can try anonymous functions for your case:
```sass
mixin($var, fn)
  .selector
    varInsideMixin $var
    fn($var)

mixin("set in param", @($var) {
  varInsideBlock $var
})
```
