### ISSUE TITLE
Support for rgba hex color

### ISSUE THREAD

**Issue by adius** [LearnBoost/stylus#1828]
It should be possible to specify rgba colors like e.g. `rgba(#00000055)`
or even `rgba(0xffffff55)` (Where the argument is a javascript number. Here in hex notation.)

**Comment by Panya** [comment]
Yep, and it's already supported (first variant) :)

**Comment by adius** [comment]
… and what about variant 2 ^^

**Comment by Panya** [comment]
@adius use-cases?

**Comment by adius** [comment]
- Three.js supports hex number colors
- Simplifies passing colors from javascript to stylus
- Less overhead for storing numbers than string
- …

**Comment by Panya** [comment]
All of this are not use cases (maybe except the second one, but in this case you can easily format any color on the JS side before passing to Stylus).
