### ISSUE TITLE
Any way to retrieve variable from compiled Styl?

### ISSUE THREAD

**Issue by inca** [LearnBoost/stylus#1833]
Say you have:

```
// styles.styl
bar = hsl(192deg, 50%, 50%)
```

And you'd like to be able to:

```
stylus.render('styles.styl').variables.bar   // hsl(192deg, 50%, 50%)
```

Is it possible?

**Comment by Panya** [comment]
No, but you can use [json](http://learnboost.github.io/stylus/docs/bifs.html#jsonpath) bif to share variables between JS and Stylus.
