### ISSUE TITLE
Support specifying custom variables when calling stylus

### ISSUE THREAD

**Issue by MetaMemoryT** [LearnBoost/stylus#1835]
like how they are in less: https://github.com/less/less.js/pull/1655

```
  --global-var='VAR=VALUE' Defines a variable that can be referenced by the file.   
  --modify-var='VAR=VALUE' Modifies a variable already declared in the file.        
```

**Comment by Panya** [comment]
You can easily define variables using [http://learnboost.github.io/stylus/docs/bifs.html#usepath](use) bif or JS API with `--use` CLI flag. I think, LESS uses that approach because before version 2.0 it has no plugin system.

**Comment by MetaMemoryT** [comment]
Thanks for the information.
