### ISSUE TITLE
No warning on indentation error

### ISSUE THREAD

**Issue by korvus** [LearnBoost/stylus#1838]
When in your .styl you write two nested selectors, there is some strange behaviors as below:

```css
#parent
  margin 0em
    .child
      margin 10px
```

Will generate

```css
#parent margin 0em .child {
  margin: 10px;
}
```

Curiosly, there is a warning when you add a colon in the first couple properties-value.
For example:
```css
#parent
  margin: 0em /* < note the ":" */
    .child
      margin 10px
```

Will output this legal warning:
ParseError: test.styl
[...]
unexpected "indent"

**Comment by Panya** [comment]
http://stackoverflow.com/questions/23028298/stylus-break-on-syntax-error-similar-to-less/23703545#23703545

TL; DR
If you want to prevent these "errors" use CSS-like syntax or write `:` in a property declaration.
