### ISSUE TITLE
Filename option in sourcemaps

### ISSUE THREAD

**Issue by iamvdo** [LearnBoost/stylus#1840]
Just a quick question: it seems that when dealing with sourcemaps, we should pass `filename` option, but Stylus checks if file exists. Why ?

How to deal with string/stdin, without a file ?

Thanks

**Comment by Panya** [comment]
> but Stylus checks if file exists. Why ?

The `filename` option is needed to correctly resolve paths of imports. Stylus doesn't check that the file exists.

> How to deal with string/stdin, without a file

You can use JS API and write something like:
```js
var stylus = require('stylus')
  , styl = stylus('body {color: red}');

styl
  .set('filename', 'unknown.styl')
  .set('sourcemap', true).render(function(err, css) {
    if (err) throw err;
    console.log(styl.sourcemap); // <--- sourcemap object
    console.log(css);
  });
```

**Comment by iamvdo** [comment]
This is what I've tested, but I got an `ENOENT, no such file or directory`.
That's why I'm asking ?

I will run more tests and let you know

**Comment by iamvdo** [comment]
So, it fails with inline sourcemaps. Like this:

```javascript
var stylus = require('stylus')
  , styl = stylus('body {color: red}');

styl
  .set('filename', 'unknown.styl')
  .set('sourcemap', {'inline': true}).render(function(err, css) {
    if (err) throw err;
    console.log(css);
  });
```

I get the `ENOENT, no such file or directory` error.

**Comment by lwdgit** [comment]
I get the same error when I ```.set('sourcemap', {'inline': true}```, but ```.set('sourcemap', {'inline': false}``` is ok

**Comment by lovetingyuan** [comment]
stylus does not support inline-sourcemap witout an out filename
