### ISSUE TITLE
Feature request: make JS mixins individually set vendor prefixes

### ISSUE THREAD

**Issue by aaarichter** [LearnBoost/stylus#1843]
I'm using stylus in conjunction with grunt-contrib-stylus. I know that one can set the vendor prefixes via variable but things like this does not seem to work:

```
vendor-prefixes ?= moz official
.test
  background: linear-gradient(#ff0, #0f0)

vendor-prefixes ?= webkit official
```
What I'm trying to do is to get rid of all the old legacy rules that are not generated via mixin but stylus JS.

Is it possible to set the vendor prefixes individually on the JS mixins (linear-gradient, keyframe, ...)  ?

**Comment by Panya** [comment]
By default Stylus adds vendor prefixes only to `@keyframes`, and you can control the prefixes by redefining `vendors` variable (see http://learnboost.github.io/stylus/docs/keyframes.html#expansion). I guess, `grunt-contrib-stylus` using `nib` by default for vendor prefixing. If so, you should open your request in https://github.com/tj/nib. But I suggest don't use Stylus mixins for prefixing, [autoprefixer](https://github.com/postcss/autoprefixer) is the best tool for this task. And we already have a Stylus plugin for autoprefixer [autoprefixer-stylus](https://github.com/jenius/autoprefixer-stylus).

**Comment by aaarichter** [comment]
thanks - that's a really nice tool - especially that it postprocesses the css
