### ISSUE TITLE
Array doc

### ISSUE THREAD

**Issue by yukulele** [LearnBoost/stylus#1847]
Stylus doc no seem to refer array (or list)

<a href="https://learnboost.github.io/stylus/docs/iteration.html">Iteration page</a> show shyly a simple example for array (`for num in 1 2 3`).

does bracket syntax exist? (`foo = [1, 2, 3]`).
how to access to element?
```stylus
col = #f00 #f80 #ccc red #ff04c2;
foo{
  color: col[2];
  background: color.3; /// does it works???
}
```
what about multi dimensional array?

**Comment by Panya** [comment]
https://learnboost.github.io/stylus/docs/operators.html#subscript-
