### ISSUE TITLE
Cannot Output Integer as String in Data Attribute Selector

### ISSUE THREAD

**Issue by oliverbenns** [LearnBoost/stylus#1853]
Say I have the following:

```
	for num in (1..360)
		.pie[data-start={num}]
			transform:rotate((num)deg);
```

There is no way (to my understanding) that I can output the data attribute as a string, which is required for the browser to pick it up.

**Comment by Panya** [comment]
Yep, we don't have string interpolation yet, but you can write something like this:

```sass
for num in (1..360)
  .pie[data-start=\"{num}\"]
    transform:rotate((num)deg);
```

**Comment by oliverbenns** [comment]
Thank you for your prompt answer :)
