### ISSUE TITLE
Normalize syntax in docs, consider normalizing actual syntax

### ISSUE THREAD

**Issue by corysimmons** [LearnBoost/stylus#1858]
It's fine to show off that Stylus can accept or not accept whatever syntaxes, but I feel like this should be normalized throughout the docs with `key: val` syntax (since that's what most libs use).

Also, maybe we should consider normalizing the actual syntax and removing the ability to use curly braces and remove colons.

It really sucks that Emmet is effectively useless on CodePen for me because the syntax is so random. It just disperses us.

**Comment by Panya** [comment]
> It's fine to show off that Stylus can accept or not accept whatever syntaxes, but I feel like this should be normalized throughout the docs with key: val syntax (since that's what most libs use).

This is already fixed in the `rc-1.0` branch.

> Also, maybe we should consider normalizing the actual syntax and removing the ability to use curly braces and remove colons.

Yep, in `rc-1.0` colons are not optional.

**Comment by eddiemonge** [comment]
Is there a discussion somewhere about why colons are no longer optional? If you make that non-optional, then really what is the difference between Stylus and Sass?
