### ISSUE TITLE
Shouldn't @keyframes bubble out of @media blocks?

### ISSUE THREAD

**Issue by maranomynet** [LearnBoost/stylus#1865]
I notice that @keyframes defined inside a @media block are rendered as is - and thus not working in IE10 and IE11.

```stylus
@media screen {
  
   @keyframes foobar {
      from { padding: 10px }
      to { padding: 0px }
   }

}
```

It seems that it would be useful if Stylus could bubble @keyframes up to the root level (above the current @media block.

**Comment by Panya** [comment]
You mean that we should ignore `@media screen` in this case and leave just:
```styl
@keyframes foobar {
  from { padding: 10px }
  to { padding: 0px }
}
```
?

Also, according the spec (http://www.w3.org/TR/css3-mediaqueries/) it seems there is no restriction for `@keyframes` (more likely it's just buggy IE)

**Comment by maranomynet** [comment]
Ah. OK.
My bad then. :-)
