### ISSUE TITLE
Math bug

### ISSUE THREAD

**Issue by rzkt** [LearnBoost/stylus#1866]
In Stylus, 1 / 3 equals 0.333333333333333 and 0.333333333333333 * 3 equals 0.999999999999999.
Whilst 1/3 should equal 0.3333333333333333, thus 0.3333333333333333 * 3 equals 1. 

The same bug also occurs when the divisor is a multiple of three.

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. The fix will be in the next release.
