### ISSUE TITLE
failed to locate @import file /node_modules\stylus\lib/functions.styl

### ISSUE THREAD

**Issue by florentpoujol** [LearnBoost/stylus#1868]
On Win7, with stylus 0.50.0, I got this error:

```failed to locate @import file /node_modules\stylus\lib/functions.styl```

Seems similar to https://github.com/LearnBoost/stylus/issues/356 but note that the path is not adsolute this time.

This append without using any @import, nor any functions.

Thank for your help.

**Comment by Panya** [comment]
I can't reproduce this with Win7, Stylus 0.50.0, Node 0.12.0 and npm 2.5.1 (fresh install). Try to reinstall Stylus or update Node/npm.

**Comment by florentpoujol** [comment]
Ok my bad, Stylus runs just fine in node.

My error is probably due to browserify. I think I need to turn off/ignore imports like shown here https://github.com/LearnBoost/stylus/pull/994 (even if this particular example doesn't work for me).

Maybe someone can alter the title to something like ```"failed to locate @import" error and browserify```.

**Comment by Panya** [comment]
Well, looks like it's bug in `browserify` after all (not correct `__dirname` on windows).

BTW if you're using Stylus in browser, probably, is better to use official client-side version (https://github.com/learnboost/stylus/tree/client, see example of usage on http://learnboost.github.com/stylus/try.html).

**Comment by KenanYusuf** [comment]
Looks like browserify is still problematic with client-side stylus - this time not a windows issue.

`var stylus = require('stylus')`

gives me the same error as stated in this issue.

`failed to locate @import file /node_modules/stylus/lib/functions.styl`

OS: OS X El Capitan
Browserify: 13.1.1
Stylus: 0.54.5

@florentpoujol I appreciate it was some time ago, but any fix?

**Comment by Panya** [comment]
client-side Stylus doesn't support imports. You should use a build from `client` branch.
