### ISSUE TITLE
Concatenate but not process/compile into css

### ISSUE THREAD

**Issue by bignimbus** [LearnBoost/stylus#1869]
```
// bar.styl
@import 'foo.styl'
.some-class
    color: #444

// foo.styl
$some_color = #333
.some-other-class
    color: $some_color
```

Desired output:

```
// main.styl
$some_color = #333
.some-other-class
    color: $some_color
.some-class
    color: #444

```

For simple hosting of a single styl file without worrying about relative paths or imports breaking.

**Comment by Panya** [comment]
Sorry, but this is out of Stylus' scope. You can easily write a script that would read a file and replace `@import ...` to its content. To get the imports you can also use `stylus --deps <some-file>`.

**Comment by bignimbus** [comment]
Thanks for the input.  FWIW, I wrote utility to resolve @import statements in Stylus and other stylesheet source files, in case anyone else is looking for this feature: https://github.com/bignimbus/import-resolve
