### ISSUE TITLE
Feature: ‘Pure-mixin import’ statement

### ISSUE THREAD

**Issue by andreyvit** [LearnBoost/stylus#605]
Add an import statement that imports all regular classes as mixins. [Similar feature request for LESS.js](https://github.com/cloudhead/less.js/issues/622) — they call it `@use`.

Given this (buttons.styl):

    .my-button
        color #fff
        background red

and this (large_screen.styl):

    @use "buttons.styl"

    .my-other-button
        my-button()   # or maybe: @extend .my-button
        background blue

I want to produce large_screen.css:

    .my-other-button {
        color: #fff;
        background red;
        background: blue;
    }

and I also want to compile buttons.styl directly to produce buttons.css:

    .my-button {
        color: #fff;
        background: red;
    }

One of my users tried to do that (with LESS) to produce separate stylesheets for different kinds of devices. I can actually see many cases where this feature would be handy.

**Comment by Panya** [comment]
We have placeholder selectors for this task.
